### ISSUE TITLE
After update, not receiving emails anymore

### ISSUE THREAD

**Issue by etique57** [andryyy/mailcow-dockerized#1065]
Hello,

After updating mailcow last week (using the update script) I was unable to receive emails for unknown reason.

Reverting back to the previous configuration, mailcow automatically rebuilt a proper docker farm and everything was back to normal.

How can I find my current version number, so that I can see what needs to be done to get the latest configuration working?

Thanks!

**Comment by tkorves** [comment]
This "feature" will be added in a future release - there's no ETA yet.
