### ISSUE TITLE
Watchdog: rspamd-mailcow service hit the error rate limit

### ISSUE THREAD

**Issue by phipag** [andryyy/mailcow-dockerized#1151]
Hey,

every time I reboot my mailcow vm i get a few minutes after the reboot a message from the watchdog that the rspamd service has been restarted. I have tested this on 2 fresh mailcow installations and it happend on both. However, the rspamd service is running well also before the watchdog restart.

This happens for about 1 month now.

**Comment by Geitenijs** [comment]
Also having this issue

**Comment by hachre** [comment]
Do you receive a very high amount of mail?

**Comment by Geitenijs** [comment]
I receive about 1 mail per 5 mins

**Comment by hachre** [comment]
I guess we'll need watchdog and rspamd logs from the time when it happens:
```
docker-compose logs --tail=100 watchdog-mailcow > watchdog.log
docker-compose logs --tail=100 rspamd-mailcow > rspamd.log
```

And then post them here.

**Comment by Geitenijs** [comment]
I don't know if it has to do with the latest patches, but it seems to work properly now. I've already restarted mailcow over 20 times.
