### ISSUE TITLE
Server syncing

### ISSUE THREAD

**Issue by NicoDreamzZ** [andryyy/mailcow-dockerized#1266]
Hey there,
at the moment I have one mailcow mailserver. Because my hoster went offline today for 5 hours and I couldn't receive any mails, I decided to get a second server for redundancy. Is there a way to sync all mailboxes and domains between two mailcow servers? I know there is an option to create synchronizations but I think these are not what I need. It would be nice to have an option to sync all mailboxes automatically to a backupserver and catch emails from there if there are any that are not on the productive server.

I hope you understand what I mean, my english is not the best 😃

**Comment by lavdnone** [comment]
You need servers to have access to same email files and to same database.
Thankfully mailcow db structure is compatible with for example galera cluster in mariabd
And mailbox dovecot email storage format works fine with something like glusterfs
That would be the direction, how we have this setup through many servers and storage pools.

For your purpose you might be better of with something like backup MX: just start separate mailcow on another server, add domain and set it as backup MX, put second server IP as second MX record for your domain.
If your main server is down - emails will accumulate on the backup MX server until they successfully get to main server when it is up.
If you put smtp.yourdomain.com to return two IPs of main and backup MX server, if main one is down people will send out through backup server.
They will not get new emails, but at least emails are not lost, users can send emails, and warn that they are down.

**Comment by mkuron** [comment]
Backup MX is supported. Full recundancy is much more complex and not supported, see #174 and #669. As long as your downtimes are less than two days at once, you don‘t even really need a backup MX though: other mailservers will retry to deliver messages to your server when it becomes available again.
