### ISSUE TITLE
alias forwarded not part of ACL

### ISSUE THREAD

**Issue by normanu** [andryyy/mailcow-dockerized#1416]
I have some mail addresses which get forwarded to a external account.
But offcourse I would like to be able to send through the server.
These alias addresses I can not add to a mailbox, that it would be allowed to send as that user.
Is there someway of fixing that?

example:

info@domain -> user@gmail.com

in the gmail I would like to add info@domain as a alias so I can send mail under that user by maybe logging in as user@domain.
But I can't add info@domain as it is going to a external domain.

**Comment by andryyy** [comment]
I will check and try to reproduce it.

You can setup a mailbox and check “don’t check sender for this domain” as a workaround.
