### ISSUE TITLE
Netfilter log verbosity

### ISSUE THREAD

**Issue by toastie89** [andryyy/mailcow-dockerized#1492]
Hi All,

I've tried to figure out why some hosts get blocked by the Netfilter container. From the logs, see below, I just see rule id 3, but no details which service was triggered in what manner.

```
20.6.2018, 07:29:17 | warn | 9 more attempts in the next 600 seconds until 217.xxx.xxx.0/20 is banned
20.6.2018, 07:29:17 | warn | 217.xxx.xxx.xxx matched rule id 3
```

While I found the rules in [netfilter/server.py](https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/netfilter/server.py) it would be helpful to see the service (e.g. Dovecot) and trigger (e.g. Aborted login) in the log.

BR, Dominik

**Comment by andryyy** [comment]
Hi,

Yes, that will be changed in the future. :-)
