### ISSUE TITLE
Weird postfix warning

### ISSUE THREAD

**Issue by lucianlazar1983** [andryyy/mailcow-dockerized#1524]
Hi there,
I have upgraded to latest version and now i am seeing this into postfix logs:
warning: btree:/var/lib/postfix/smtpd_scache is unavailable. open database /var/lib/postfix/smtpd_scache.db: File exists

Should i try removing the database /var/lib/postfix/smtpd_scache.db manually?
Thank you!

**Comment by mitchellurgero** [comment]
This article: https://www.faqforge.com/linux/solution-for-fatal-open-database-varlibpostfixsmtpd_scache-db-file-exists/

Has a possible solution. BUT I HAVE NEVER DONE IT so be careful. Do backup BEFORE doing,
