### ISSUE TITLE
Domain hosting with mailcow

### ISSUE THREAD

**Issue by jobidon** [andryyy/mailcow-dockerized#1594]
I am in the process of migrating from Mailinabox to mailcow and one of the nice feature of MiaB is that whenever you add a domain to it, a website for that domain is automatically added. 
Being bundled with nginx, it should be straightforward to replicate this functionality in Mailcow. One way, is that I could manually add each domain in `data/conf/nginx/site.conf`, but there must be an easier way to do that, since the domains are already known by mailcow.

The current behavior is that nginx redirects all requests to the mailcow SoGo page for all domains. I would like to redirect all domains to a corresponding sub directory (presumably under `data/web`). What would be the recommended way to do this?

**Comment by andryyy** [comment]
Hi,

What is the purpose of this website (per domain)? Can you explain? :-)

**Comment by jobidon** [comment]
Nothing particular, just any web content.
for example, if domain1.com and domain2.com are both hosted, mailcow could serve the pages for http://www.domain1.com and http://www.domain2.com (normal websites), as well as http://domain1.com/SOGo for the mail UI, etc.

**Comment by andryyy** [comment]
I added this to the docs. That's the best we can do. mailcow is a mail cow, not a web cow. :-)
