### ISSUE TITLE
Forwarding mail won't work " Execution of Sieve filters was aborted due to temporary failure "

### ISSUE THREAD

**Issue by simon-india** [andryyy/mailcow-dockerized#1627]
Guys having a issue with forwarding when I enable it I get this response and I can't receive any mail 

![image](https://user-images.githubusercontent.com/23007053/43599487-645ef1e8-96a5-11e8-9bdc-f70f731ca351.png)
![image](https://i.imgur.com/IsRHNys.png)
![image](https://user-images.githubusercontent.com/23007053/43599708-1faf097e-96a6-11e8-9fed-9d3d64be0568.png)

**Comment by andryyy** [comment]
IPv6 is disabled, right? Do not use that parameter anymore, I changed it and will push an update soon.

**Comment by simon-india** [comment]
Thanks but No IPv6 enabled but my network don't have ipv6 but I don't disable IPv6

Should I ?

And I have to ask how can i help.

**Comment by andryyy** [comment]
Can you update and check the docs about how to disable IPv6?
