### ISSUE TITLE
get_ipv4 & get_ipv6 with https

### ISSUE THREAD

**Issue by Knight1** [andryyy/mailcow-dockerized#1634]
Hey :)

Every Domain supports TLS excluding ipecho.net and *.mailcow.email
How about adding https://?
https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh#L69

https://github.com/mailcow/mailcow-dockerized/blob/master/data/Dockerfiles/acme/docker-entrypoint.sh#L70 There is a - at the end of the line. Is this a typo?

**Comment by andryyy** [comment]
It is indeed a typo, thanks.

Adding HTTPS is not necessary for this type of service. We are querying our remote IP. :-)

I removed the "-" from the script.

**Comment by Knight1** [comment]
Not necessary but also not wrong to implement that. 
I also don't understand why ip(4|6.mailcow.email does not have TLS enabled. I was able to mitm the dns_diagnostics.php output. Nothing special but also avoidable and https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/ajax/dns_diagnostics.php#L84 does not validate the input like the acme docker-entrypoint.sh.

**Comment by andryyy** [comment]
The only output is the remote address we already use to connect to this server. There is absolutly no need to encrypt this connection... It is unnecessary to add TLS overhead to this query, seriously.

Plus: Why would dns_diagngostics.php match acme-mailcow? They both do different things.
