### ISSUE TITLE
MAILDIR_GC_TIME Not added to config after update

### ISSUE THREAD

**Issue by ntimo** [andryyy/mailcow-dockerized#1821]
Hello,
I just rand the update.sh and the new MAILDIR_GC_TIME config variable was not added to my mailcow.conf. I am going to add it manually. But what exactly does it? If I understand it correctly it will delete all old mailboxes and domain when I delete them in the mailcow config. Does this also applies to email that users have in they trash?

Thanks

**Comment by andryyy** [comment]
Fixed it.

We now move old domains and mailboxes (when deleted via UI) to /var/vmail/_garbage and run an hourly cronjob to check for folders older than MAILDIR_GC_TIME  in minutes.
