### ISSUE TITLE
Watchdog emails should include timestamp(s) of when it does stuff.

### ISSUE THREAD

**Issue by mitchellurgero** [andryyy/mailcow-dockerized#1908]
**Is your feature request related to a problem? Please describe.**
Clear up watchdog alerts

**Describe the solution you'd like**
Alert (In this case I am doing email -> SMS conversion for ease of use) sent should include when the alert came up. The reason a timestamp should be included in the email is because the email might be delay (for one reason or another). Also maybe include more details if possible to watchdog alerts.

**Additional context**
(Again, I am using email to SMS (phonenumber@ispmms.tld)) (Also: I apologize for image size.)

> ![watchdog-alert](https://user-images.githubusercontent.com/4168998/47048399-e5a9aa00-d15f-11e8-99ba-a78bd1da49e2.png)

**Comment by ntimo** [comment]
Oh nice, which service are you using for this? I think adding a timestamp would be nice :-)

**Comment by mitchellurgero** [comment]
@ntimo if you are talking about the watchdog service, see the mailcow conf file on how to configure the watchdog. It’s simple a docker service that runs along side the rest of the containers.

If you are talking about the email to sms I use, it’s ISP based:
Examples: https://lifehacker.com/5506326/how-can-i-send-an-email-via-text-message

**Comment by andryyy** [comment]
I will add it. Let me add some more stuff before pushing it. :-)

**Comment by mitchellurgero** [comment]
Thanks @andryyy

**Comment by andryyy** [comment]
It does add the date/time now. It also adds an attachment with the last check loop results. Is this a problem for your service, @mitchellurgero ? I can add a parameter to disable it then.

**Comment by mitchellurgero** [comment]
@andryyy I am using my ISP for this so I am unsure what will happen guess we will find out the next time my server goes down LMAO

**Comment by mitchellurgero** [comment]
Just an FYI it does look good, updated and the watch dog service sent two good emails.

![Image](https://i.imgur.com/p47e5KS.jpg)
