### ISSUE TITLE
DNS Problem?

### ISSUE THREAD

**Issue by MrFunken** [andryyy/mailcow-dockerized#2004]
**Describe the bug**

The system seems to have issues to resolve dns requests.

warning:  dnsblog_query: lookup error for DNS query  36.145.172.185.bl.mailspike.net: Host or domain name not found. Name  service error for name=36.145.172.185.bl.mailspike.net type=A: Host not  found, try again

**How to reproduce Reproduce**
Steps to reproduce the behavior please explain how to reproduce the bug:
I have no Idea. Its an clean install

**Expected behavior**
No DNS Errors

**Logs**
clamd-mailcow_1      | Tue Nov 13 17:04:03 2018 -> ClamAV update process started at Tue Nov 13 17:04:03 2018
clamd-mailcow_1      | Tue Nov 13 17:04:08 2018 -> ^dn_expand failed
clamd-mailcow_1      | Tue Nov 13 17:04:08 2018 -> ^Invalid DNS reply. Falling back to HTTP mode.
clamd-mailcow_1      | Tue Nov 13 17:04:08 2018 -> Reading CVD header (main.cvd): Tue Nov 13 17:04:13 2018 -> ^Can't get information about database.clamav.net: Try again
clamd-mailcow_1      | Tue Nov 13 17:04:13 2018 -> ^Can't read main.cvd header from database.clamav.net (IP: )
clamd-mailcow_1      | Tue Nov 13 17:04:13 2018 -> Trying again in 5 secs...

postfix-mailcow_1    | Nov 13 17:16:42 mx1 postfix/dnsblog[410]: warning: dnsblog_query: lookup error for DNS query 36.145.172.185.bl.mailspike.net: Host or domain name not found. Name service error for name=36.145.172.185.bl.mailspike.net type=A: Host not found, try again
postfix-mailcow_1    | Nov 13 17:16:42 mx1 postfix/dnsblog[412]: warning: dnsblog_query: lookup error for DNS query 36.145.172.185.dnsbl.sorbs.net: Host or domain name not found. Name service error for name=36.145.172.185.dnsbl.sorbs.net type=A: Host not found, try again
postfix-mailcow_1    | Nov 13 17:16:42 mx1 postfix/dnsblog[413]: warning: dnsblog_query: lookup error for DNS query 36.145.172.185.dnsbl.inps.de: Host or domain name not found. Name service error for name=36.145.172.185.dnsbl.inps.de type=A: Host not found, try again
postfix-mailcow_1    | Nov 13 17:16:42 mx1 postfix/dnsblog[414]: warning: dnsblog_query: lookup error for DNS query 36.145.172.185.hostkarma.junkemailfilter.com: Host or domain name not found. Name service error for name=36.145.172.185.hostkarma.junkemailfilter.com type=A: Host not found, try again
postfix-mailcow_1    | Nov 13 17:16:42 mx1 postfix/dnsblog[415]: warning: dnsblog_query: lookup error for DNS query 36.145.172.185.wl.mailspike.net: Host or domain name not found. Name service error for name=36.145.172.185.wl.mailspike.net type=A: Host not found, try again

**System**
 - OS: Debian 9
 - Browser: Firefox

**Comment by hachre** [comment]
The typical case is an active firewall either on your server or in the provider's network blocking port 53 communication. Do you have anything like that going on? 

Has it ever worked for you and just suddenly stopped working or is this a new installation you have this problem with?

**Comment by MrFunken** [comment]
First I have tried to move a server to a different location.
As it is running on a KVM System, I just copied the system to the new location and changed the IP on the guest system.

But, that did not work and was giving me that error...

So, to make the debugging short, I have tried a clean install.
Installed a fresh Debian 9 System, installed mailcow as described in the wiki.

But, I have got the same error O.o

On the network side, there is nothing blocked or firewalled.
DNS Requests direct on the system works just fine.

I would say it is an issue with the unbound problem, as I get exactly the same error message as in #585

**Comment by andryyy** [comment]
Which provider? Some shitty providers block this traffic. Is ufw or firewalld installed and active? It is no mailcow issue, defintly a network issue. :-(

**Comment by MrFunken** [comment]
We are our own ISP.
As I already have mentioned there is no port blocking.

And no, it's definitely not a network issue

**Comment by MrFunken** [comment]
`######################################################################## 100.0%
unbound-mailcow_1    | [1542132659] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1542132659] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1542132659] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1542132660] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1542132796] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1542132796] unbound[1:0] info: server stats for thread 0: 150 queries, 3 answers from cache, 147 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1542132796] unbound[1:0] info: server stats for thread 0: requestlist max 22 avg 16.6803 exceeded 0 jostled 0
unbound-mailcow_1    | [1542132796] unbound[1:0] info: average recursion processing time 58.737021 sec
unbound-mailcow_1    | [1542132796] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1542132796] unbound[1:0] info: [25%]=7 median[50%]=78.2222 [75%]=103.111
unbound-mailcow_1    | [1542132796] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1542132796] unbound[1:0] info:    0.002048    0.004096 1
unbound-mailcow_1    | [1542132796] unbound[1:0] info:    1.000000    2.000000 1
unbound-mailcow_1    | [1542132796] unbound[1:0] info:    4.000000    8.000000 2
unbound-mailcow_1    | [1542132796] unbound[1:0] info:   32.000000   64.000000 1
unbound-mailcow_1    | [1542132796] unbound[1:0] info:   64.000000  128.000000 9
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1542133012] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1542133012] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1542133012] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1542133013] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | Receiving anchor key...
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
unbound-mailcow_1    | [1542133890] unbound[1:0] error: Could not open logfile /dev/stdout: Permission denied
unbound-mailcow_1    | [1542133890] unbound[1:0] notice: init module 0: validator
unbound-mailcow_1    | [1542133890] unbound[1:0] notice: init module 1: iterator
unbound-mailcow_1    | [1542133890] unbound[1:0] info: start of service (unbound 1.6.2).
unbound-mailcow_1    | [1542135103] unbound[1:0] info: service stopped (unbound 1.6.2).
unbound-mailcow_1    | [1542135103] unbound[1:0] info: server stats for thread 0: 322 queries, 39 answers from cache, 283 recursions, 0 prefetch, 0 rejected by ip ratelimiting
unbound-mailcow_1    | [1542135103] unbound[1:0] info: server stats for thread 0: requestlist max 82 avg 28.2261 exceeded 0 jostled 0
unbound-mailcow_1    | [1542135103] unbound[1:0] info: average recursion processing time 487.925324 sec
unbound-mailcow_1    | [1542135103] unbound[1:0] info: histogram of recursion processing times
unbound-mailcow_1    | [1542135103] unbound[1:0] info: [25%]=209.455 median[50%]=611.343 [75%]=817.672
unbound-mailcow_1    | [1542135103] unbound[1:0] info: lower(secs) upper(secs) recursions
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    0.002048    0.004096 1
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    0.016384    0.032768 3
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    0.065536    0.131072 3
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    0.131072    0.262144 1
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    1.000000    2.000000 1
unbound-mailcow_1    | [1542135103] unbound[1:0] info:    4.000000    8.000000 1
unbound-mailcow_1    | [1542135103] unbound[1:0] info:   32.000000   64.000000 5
unbound-mailcow_1    | [1542135103] unbound[1:0] info:   64.000000  128.000000 32
unbound-mailcow_1    | [1542135103] unbound[1:0] info:  128.000000  256.000000 11
unbound-mailcow_1    | [1542135103] unbound[1:0] info:  256.000000  512.000000 24
unbound-mailcow_1    | [1542135103] unbound[1:0] info:  512.000000 1024.000000 134
`

**Comment by hachre** [comment]
It appears you aren't on the latest version of the Unbound image, since you have the `/dev/stdout` problem, which was fixed recently. Please run `./update.sh` in the Mailcow directory and try again.
