### ISSUE TITLE
[solved] Backup-MX and "relay all recepients" are different options 

### ISSUE THREAD

**Issue by Adorfer** [andryyy/mailcow-dockerized#2166]
situation: 

- sogo sending mail to non-local users on backup-domains domain fails to WEB-UI errormessage

probable explanation

- sogo tries to validate the existance of the destination mbox and fails.

setup: 

- domain configured in mcd as "backup-mx" 

  -- expected behaviour: All non local know mailboxes are routed versus mailrouting table entry. 
  -- in other words: "is_mbox probes" can not work since postfix is not authorative to tell.

![grafik](https://user-images.githubusercontent.com/10302493/50965713-11c09700-14d3-11e9-87b8-a19e1281906f.png)

Note: 

- i am not sure if this is an issue that can be corrected in mailcow or if it's a missing configuration option in sogo.

**Comment by andryyy** [comment]
Hm, SOGo sometimes displays strange error messages, it shows the above msg for sender_login_mismatches, too. So it would be best to see some Postfix logs for the time it happens. :)

**Comment by Adorfer** [comment]
indeed, it looks more like an isssue in postfix: 

despite the fact that domain "yyyyyyy" is marked as "backupmx", delivery seems to be tried locally: 

NOQUEUE: reject: RCPT from mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network[172.22.1.248]: 550 5.1.1 <xxxx@yyyyyyy>: Recipient address rejected: User unknown in relay recipient table; from=<zzzzzz@yyyyyyyy> to=<xxxxx@yyyyyyy> proto=ESMTP helo=<58c967e57afc>

**Comment by andryyy** [comment]
Ah, you need to create "blind mailboxes" or check "relay all recipients" in the domain edit dialog.

**Comment by Adorfer** [comment]
i missed that option. 

![grafik](https://user-images.githubusercontent.com/10302493/50968172-92cf5c80-14da-11e9-9aaf-dfe6304b0264.png)

thanks.
