### ISSUE TITLE
SOGo loop during start "Waiting for schema update..."

### ISSUE THREAD

**Issue by marc-development** [andryyy/mailcow-dockerized#2934]
After upgrade with upgrade.sh script SOGo loop during start with message
"Waiting for schema update..."

image: mailcow/sogo:1.57

Within the SOGo container file bootstrap-sogo.sh
Section: # Wait for updated schema

Script loop because following variables not matching:
DBV_NOW=$(mysql --socket=/var/run/mysqld/mysqld.sock -u ${DBUSER} -p${DBPASS} ${DBNAME} -e "SELECT version FROM versions;" -BN)

DBV_NEW=$(grep -oE '\$db_version = .*;' init_db.inc.php | sed 's/$db_version = //g;s/;//g' | cut -d \" -f2)

In my case:
root@ab4411d6c4d1:/# echo $DBV_NOW
01092019_1240 951b2dba2578c8569ff745a6fa662f5d1256c61fbec5305637e85f92e64c2087

root@ab4411d6c4d1:/# echo $DBV_NEW
01092019_1240

As a quick and dirty workaround (sorry I´m not a software engineer) I adjusted as follows:
DBV_NOW_TMP=$(mysql --socket=/var/run/mysqld/mysqld.sock -u ${DBUSER} -p${DBPASS} 
${DBNAME} -e "SELECT version FROM versions;" -BN)

DBV_NOW=$(echo $DBV_NOW_TMP | sed 's/ .*$//')

SOGo then comes up and running after container restart

**Comment by andryyy** [comment]
1.57 is not up to date. 

It was fixed a longer time ago.

**Comment by marc-development** [comment]
I´m sorry. You are right. After updating the containers with current versions error solved. Thank you !!!

**Comment by andryyy** [comment]
Nice :)

**Comment by Lucavon** [comment]
Having the same issue with sogo 1.71. Tried running update.sh multiple times, but to no avail. 

Constantly getting this:
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | grep: init_db.inc.php: Is a directory
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | grep: init_db.inc.php: Is a directory
sogo-mailcow_1       | Waiting for schema update...
sogo-mailcow_1       | grep: init_db.inc.php: Is a directory



EDIT: I fixed this by removing the "web" directory from mailcow's data folder. I then cloned mailcow-dockerized to another location, and copied the data/web folder from there to my existing installation.

I remember something going wrong during the upgrade, but it finished without any more errors, so I assumed it worked. It appparently did not.

If you need to see the broken "web" folder, I still have a copy of it.
