### ISSUE TITLE
OAuth Provider does not support OpenID Connect

### ISSUE THREAD

**Issue by Keridos** [andryyy/mailcow-dockerized#3605]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:
Using Mailcow as an OAuth Provider does not work with OpenID Connect although the upstream php project (https://github.com/bshaffer/oauth2-server-php) seems to support it. Seems like mailcow is not permitting the scope "openid" which is required for that standard.

**Docker container logs of affected containers**:
From nginx log:
` "GET /oauth/authorize?scope=openid+profile&state=NDl3E1teRUqa5ebkUzbLlalj8L481e1tEPzW_S_RUHI.L2UvJF6sHpY.security-admin-console&response_type=code&client_id=3de66ba91b75&redirect_uri=https%3A%2F%2Fdomain.tld%2Fauth%2Frealms%2Fmaster%2Fbroker%2Fmailcow%2Fendpoint&nonce=D5EPJoMvwpLJFRjQSxwsMw HTTP/1.1" 302 182 "https://domain.tld/auth/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2Fdomain.tld%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F%23%2Frealms%2Fmaster%2Fusers%2F668d53fe-9f61-417e-84ae-20f252a3dfef%2Fuser-attributes&state=1567ed7a-979d-45e1-8f94-6b3178309cab&response_mode=fragment&response_type=code&scope=openid&nonce=36a58d95-6686-4804-9ad2-4f91a8c9a08f&code_challenge=kA-Z5llaC5ViaABsPdfFPzA5SZLLwZEuIl6Q_Ekxwj0&code_challenge_method=S256" "Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0"`

**Reproduction of said bug**:
Try to add mailcow as an oauth provider in an external app (like keycloak) and try to connect to it via openid connect.

**System information**:
alpine linux, using docker

| Question | Answer |
| --- | --- |
| My operating system | alpine linux, |
| Is Apparmor, SELinux or similar active? | No|
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 2CPU 4G RAM |
| Docker Version (`docker version`) | 19.03.5 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | Traefik v2.2 |

- Output of `git diff origin/master`, any other changes to the code?
```diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 8cb0164f..0dc020c9 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -144,9 +144,9 @@ lmtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
 smtpd_tls_mandatory_ciphers = high
 
-smtp_tls_protocols = !SSLv2, !SSLv3
+smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1
 lmtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
-smtpd_tls_protocols = !SSLv2, !SSLv3
+smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1
 
 smtpd_tls_security_level = may
 tls_preempt_cipherlist = yes

@@ -196,3 +196,5 @@ smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
diff --git a/docker-compose.yml b/docker-compose.yml
index 769694bd..95b8f0c8 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -282,6 +282,7 @@ services:
       hostname: ${MAILCOW_HOSTNAME}
       networks:
         mailcow-network:
+          ipv4_address: ${IPV4_NETWORK:-172.22.1}.247
           aliases:
             - postfix
 
@@ -330,10 +331,18 @@ services:
         - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
         - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
         - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
-      ports:
-        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
-        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
+#      ports:
+#        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
+#        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
       restart: always
+      labels:
+        - "traefik.enable=true"
+        - "traefik.http.services.mailcow-nginx.loadbalancer.server.port=8080"
+        - "traefik.http.routers.mailcow-nginx.rule=Host(`mail.domain.tld)"
+        - "traefik.http.routers.mailcow-nginx.tls=true"
+        - "traefik.http.routers.mailcow-nginx.tls.certResolver=le"
+        - "traefik.http.routers.mailcow-nginx.tls.options=default"
+        - "traefik.http.routers.mailcow-nginx.middlewares=stsheaders"
       networks:
         mailcow-network:
           aliases:

```

**Comment by andryyy** [comment]
That's not a bug. We just - as stated in the UI - have the profile scope.

**Comment by Keridos** [comment]
Could this be interpreted as a feature request then?

**Comment by andryyy** [comment]
It is not that you just need to provide a scope. Openid asks for some values we don't provide for it. 

You can work on it and create a PR if you like.

**Comment by dnwk** [comment]
I am wondering if there are any further interests on full OpenID Connect support? Or make it a full SAML IdP?

**Comment by berlincount** [comment]
I would also be in favor of full OpenID Connect support.

https://github.com/mailcow/mailcow-dockerized/issues/4535 mentions the needed aspects.
