### ISSUE TITLE
OAuth can fail due to wrong content type

### ISSUE THREAD

**Issue by this-user** [andryyy/mailcow-dockerized#3716]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

The OAuth flow can fail, because the client is unable to process the information returned via the `/oauth/profile endpoint`. The reason for this is that the JSON structure is returned with content type set to `text/html`. 

Notably, this happens when trying to connect Gitlab to Mailcow, which will throw an error that the email address is empty even when path and mappings are configured correctly. So far, I have not experienced the same problem with any other client.

**Docker container logs of affected containers**:

Happens solely on the client side.

**Reproduction of said bug**:

- Add a new OAuth client on the Mailcow side
- Configure Mailcow as authentication provider on the Gitlab side like so

```yaml
gitlab_rails['omniauth_enabled'] = true
gitlab_rails['omniauth_allow_single_sign_on'] = ['Mailcow']
gitlab_rails['omniauth_block_auto_created_users'] = false
gitlab_rails['omniauth_providers'] = [{
   'name' => 'Mailcow',
   'app_id' => '<YOUR-ID-HERE>',
   'app_secret' => '<YOUR-SECRET-HERE>',
   'args' => {
       "scope" => "profile",
       client_options: {
          'site' => 'https://<YOUR-DOMAIN-HERE>',
          'user_info_url' => '/oauth/profile',
          'authorize_url' => '/oauth/authorize',
          'token_url' => '/oauth/token'
       },
       user_response_structure: {
          root_path: [],
          id_path: "identifier",
          attributes: { nickname: 'username', email: "email", name: "displayName" }
       },
       name: 'Mailcow',
       strategy_class: "OmniAuth::Strategies::OAuth2Generic"
    }
}]
```
- Attempt to log in via MC
- Login fails with a message that the email address may not be blank

The solution is setting the content type to `application/json` for the profile endpoint. Logging in then works as expected.

```diff
diff --git a/data/web/oauth/profile.php b/data/web/oauth/profile.php
index 3628e58b..694f9859 100644
--- a/data/web/oauth/profile.php
+++ b/data/web/oauth/profile.php
@@ -10,7 +10,8 @@ $stmt = $pdo->prepare("SELECT * FROM `mailbox` WHERE `username` = :username AND
 $stmt->execute(array(':username' => $token['user_id']));
 $mailbox = $stmt->fetch(PDO::FETCH_ASSOC);
 if (!empty($mailbox)) {
  if ($token['scope'] == 'profile') {
+    header('Content-Type: application/json');
     echo json_encode(array(
       'success' => true,
       'username' => $token['user_id'],
```

I do not know whether the OAuth 2 specification strictly requires this, or whether Gitlab is overly strict. I have also not verified that this does not cause issues with any other clients. But given that the endpoint is, in fact, returning pure JSON, this would appear to be the correct content type to set, so any issues from this change seem unlikely, or would rather mean that the client itself is not well-behaved.

**Comment by andryyy** [comment]
Hi,

Thank you! That's a good catch. I think it is actually very important to respond with the correct content type. I will fix it in a bit!
