### ISSUE TITLE
Is an IMAP API something that could be added?

### ISSUE THREAD

**Issue by ClarLabs** [andryyy/mailcow-dockerized#4243]
Hello Mailcow

We use a mailcow instance as our main email server and everything about it is amazing, one thing that would be a nice to have is the use of an IMAP API something like https://github.com/postalsys/emailengine.

Is this something that could potentially be added in the future?

I will look forward to your reply

Best Regards
Chris

**Comment by andryyy** [comment]
Hi,

Thank you! :)

Hm, if I see it correctly, you can use emailengine on top of mailcow?

**Comment by mkuron** [comment]
Duplicate of #3917.

The main reason why we don‘t have this is that there is no standardized way to access mail via an HTTP API. So you can only use the API in code you write yourself, and in that case we recommend just connecting to IMAP directly.
