### ISSUE TITLE
Domain administrator removes SOGo access if ACL for managing SOGo access was taken

### ISSUE THREAD

**Issue by gioqw** [andryyy/mailcow-dockerized#4291]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

If a domain administrator is missing the ACL for "Allow management of SOGo access" and he/she edits a mailbox with SOGo access enabled, it will be disabled after saving.

The expected behavior is that SOGo access rights of the mailbox are not touched / changed by that domain administrator.

Latest commit was 28d71196f6d9b1e8ecdbfa165dc0e02a68668b08

## Logs

No errors are given, the logs only show that sogo_access is now "0".

## Reproduction

1. Create a domain administrator and remove the ACL for "Allow management of SOGo access".
2. Login with that newly created domain administrator.
3. Edit or just save any mailbox which has SOGo access.
4. The mailbox now has no more access to SOGo.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04.3 LTS |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8 cores, 16GB RAM |
| Docker Version (`docker version`) | 20.10.9 |
| Docker-Compose Version (`docker-compose version`) | 1.29.2 |
| Reverse proxy (custom solution) | No |

```
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 00eb8a93..090c0647 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,6 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
 
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = XXXX
+
```

**Comment by andryyy** [comment]
Very good catch. Will fix it tomorrow. :) Thanks

**Comment by andryyy** [comment]
Oh, sorry, it is already fixed, forgot the reference. :(
