### ISSUE TITLE
Mailboxes > Login: Admin login is forbidden

### ISSUE THREAD

**Issue by RafaelKr** [andryyy/mailcow-dockerized#4297]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

Mailcow version: latest at the time of writing this issue (4019dc5477f8db0f3aef8af67f99cd4c0e599f42)

When I'm logged into the mailcow UI as admin and want to login into a users webmail via login button it opens a new Tab with the route `/sogo-auth.php?login=mail@example.com` which says "Admin login is forbidden". When switching tabs back to mailcow UI and click the "log out" icon in the upper right and then reload the SOGo-Tab it works.

## Reproduction

- Login to the mailcow UI as admin
- Click `Configuration` > `Mail Setup`
- Switch to `Mailboxes` tab
- Click the green `Login` button
- Click `Login to webmail`, this should open a new SOGo tab which says "Admin login is forbidden"
- Go back to the mailcow UI tab
- Use the Logout-Icon in the upper right corner
- Go forth to the previously opened SOGo tab and reload it
- Voilà - you should be logged in now

## System information

Not required

**Comment by andryyy** [comment]
Hi, is ALLOW_ADMIN_LOGIN set to y in mailcow.conf?

**Comment by RafaelKr** [comment]
The following line is set in my mailcow.conf: `ALLOW_ADMIN_EMAIL_LOGIN=n`

But then I don't understand why I can still login via the described "workaround"?

**Comment by andryyy** [comment]
Perhaps it is the previous session you had active before trying SSO

**Comment by RafaelKr** [comment]
Hmm okay. I've now set `ALLOW_ADMIN_EMAIL_LOGIN=y` and I additionally have a `SOGo` button now, which is nice.

But then it's most probably a bug that I can use the workaround to sign into any users SOGo without a password although `ALLOW_ADMIN_EMAIL_LOGIN=n` is set.

**Comment by andryyy** [comment]
Can you check if it just logs you in to the previous/old session or did you try with multiple mailboxes?

**Comment by RafaelKr** [comment]
I can sign in to multiple mailboxes simultaneously. I signed in to 3 different mailboxes. I also reloaded each tab afterwards and they kept their session. I've also sent 2 mails from different mailboxes and they sent from the correct account.

**Comment by andryyy** [comment]
That's a good catch, will be fixed in a bit!

**Comment by RafaelKr** [comment]
@andryyy Great! Now it's not accessible anymore.

Then this button can probably also be removed?

![image](https://user-images.githubusercontent.com/14234815/138692906-f28d8dbe-93d4-49e9-9fa7-d5f9da55686a.png)
