### ISSUE TITLE
ssl/record/rec_layer_s3.c:1544:SSL alert number 45

### ISSUE THREAD

**Issue by Julen10** [andryyy/mailcow-dockerized#4300]
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [x] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary

I have troubles on sending emails configured with mailcow since 3 days ago (I was using mailcow for like 6 month).
## Logs

Log from postfix:
warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1544:SSL alert number 45:
## Reproduction

Just sending an email that is configured with ssl/tls on port 465.
## System information

| Question | Answer |
| --- | --- |
| My operating system | Centos 4.18.0-240.15.1.el8_3.x86_64 |
| Is Apparmor, SELinux or similar active? | SELinux as permissive |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | --- |
| Server/VM specifications (Memory, CPU Cores) | --- |
| Docker Version (`docker version`) | 20.10.5 |
| Docker-Compose Version (`docker-compose version`) | 1.28.5 |
| Reverse proxy (custom solution) | No |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
```
-    enable_ipv6: true
+    enable_ipv6: false
```

- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by Adorfer** [comment]
please be a bit mor verbose verbose in the log. What is the scenario? You defined a mail-transport via tls/465 to deliver you outgoing mail to a smarthost?

**Comment by Julen10** [comment]
Hi @Adorfer 
I have a server hosting dockerized mailcow and working correctly 6 months before, hosting domain.com mails.
I have another server hosting a website who is sending mails configured with tls/465 to mail hosted on the mailcow server too, like from mail@domain.com to mail_2@domain.com.
Suddenly, this warning appears that doesn´t send the email.
It happend to me on 2 different mailcow servers.

**Comment by andryyy** [comment]
Check your certificate. 

There is no change that causes this.

**Comment by Julen10** [comment]
The certificate that mailcow issues automatically or the certificate on the sender server?

**Comment by MAGICCC** [comment]
The mailcow server.
Seems the cert is expired `alert certificate expired`

**Comment by Julen10** [comment]
I followed this one and seems to work again:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/

I don´t really know how to reissue the cert, because mailcow is suppose to do it by it´s own...

**Comment by andryyy** [comment]
Yes, but you need to make sure it can actually do that. 😄

**Comment by MAGICCC** [comment]
You may check the logs from the acme container and you can force a renewal using this: https://mailcow.github.io/mailcow-dockerized-docs/firststeps-ssl/#force-renewal

Also we don't provide support here on GitHub
Either ask in our [telegram channel](https://telegram.me/mailcow) or in [our forum](https://community.mailcow.email/)

**Comment by twixi** [comment]
i have too error, im update.sh, but not work(
`warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1544:SSL alert number 45:`

Force renewal - did not help(

**Comment by Julen10** [comment]
> i have too error, im update.sh, but not work( `warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1544:SSL alert number 45:`
> 
> Force renewal - did not help(

Try to make the following:
https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/

**Comment by twixi** [comment]
> Try to make the following:
> https://mailcow.github.io/mailcow-dockerized-docs/u_e-reeanble-weak-protocols/
noting...

`warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1544:SSL alert number 45:`

acme:  `Certificates were successfully validated, no changes or renewals required, sleeping for another day.`

**Comment by twixi** [comment]
any news? im create new vps server, ubuntu 18.04m install from fresh instruction from mailcow, then generate_config.sh and restore backup...  after im run update.sh and i now have this error:
09.02.2022, 21:58:43	info	disconnect from unknown[ip] ehlo=1 starttls=0/1 commands=1/2
09.02.2022, 21:58:43	info	lost connection after STARTTLS from unknown[ip]
09.02.2022, 21:58:43	warning	warning: TLS library problem: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:../ssl/record/rec_layer_s3.c:1544:SSL alert number 45:
09.02.2022, 21:58:43	info	SSL_accept error from unknown[ip]: -1
09.02.2022, 21:58:42	info	connect from unknown[ip]

im send from wordpress email and have debug:

SMTP Debug:
2022-02-09 20:05:10 Connection: opening to ssl://mail.server.com:465, timeout=300, options=array (
)
2022-02-09 20:05:15 Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2022-02-09 20:05:15 Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): Failed to enable crypto
2022-02-09 20:05:15 Connection: Failed to connect to server. Error number 2. "Error notice: stream_socket_client(): unable to connect to ssl://mail.server.com:465 (Unknown error)
2022-02-09 20:05:15 SMTP ERROR: Failed to connect to server: (0)

im tryed SSL Force with data/assets/ssl/force_renew
