### ISSUE TITLE
Allow "one dot" FQDN

### ISSUE THREAD

**Issue by ScrumpyJack** [andryyy/mailcow-dockerized#4302]
my $MAILCOW_HOSTNAME is my-super-duper-mail-server.com but update.sh won't allow for "one dot" FQDNs.

Not sure why mailcow is trying to enforce mail.my-super-duper-mail-server.com

Please can you allow for "one dot" FQDN, or allow me to override the check?

**Comment by MAGICCC** [comment]
I'll close this since we also have https://github.com/mailcow/mailcow-dockerized/issues/1572 + https://github.com/mailcow/mailcow-dockerized/pull/3284

**Comment by ScrumpyJack** [comment]
Oops, sorry yes I had missed that issue. Thanks for the pointer.
