### ISSUE TITLE
Apache2 ReverseProxy issues

### ISSUE THREAD

**Issue by JonasBVS** [andryyy/mailcow-dockerized#771]
I have 2 configs, 1 working and 1 rendering SOGo to be broken.

The first(working) has directive "ServerName admin.example.org" proxying http://127.0.0.1:8080/, and that works fine.

the second config has directive "ServerName webmail.example.org" proxying http://127.0.0.1:8080/SOGo and renders SOGo to be broken(see image)

![image](https://user-images.githubusercontent.com/14073593/33166141-7ca85862-d039-11e7-9d47-83251e043945.png)

Apache modules active: "proxy", "proxy_http" and "headers"

The 2nd config looks like this

\<IfModule mod_ssl.c\>
        \<VirtualHost _default_:443\>
  
                ServerAdmin webmaster@localhost
                ServerName webmail.example.org

                ProxyPass / http://127.0.0.1:8080/SOGo
                ProxyPassReverse / http://127.0.0.1:8080/SOGo

                # If you plan to proxy to a HTTPS host:
                SSLProxyEngine On

                # If you plan to proxy to an untrusted HTTPS host:
                #SSLProxyVerify none
                #SSLProxyCheckPeerCN off
                #SSLProxyCheckPeerName off
                #SSLProxyCheckPeerExpire off

                #ProxyPreserveHost On
                #ProxyAddHeaders On

                RequestHeader set X-Forwarded-Proto "https"

**Comment by SamuelNitsche** [comment]
I have the same problem. I tried to use trailing slashes in the apache config (i thought maybe path issues) but it did'nt help.

**Comment by TiiFuchs** [comment]
As I mentioned in #768 before this is because /SOGo/... uses resources (js, css) from /SOGo.woa/... And therefore you cannot proxy to /SOGo/. 

You have to specify your Proxy like this:

  ProxyPass / http://127.0.0.1:8080/
  ProxyPassReverse / http://127.0.0.1:8080/
